### ISSUE TITLE
Fig2.13 (Book1) iris_logreg.ipynb

### ISSUE THREAD

**Issue by karm-patel** [pyprobml-review/pyprobml-review#2]
I am working on this figure

**Comment by nitish1295** [comment]
As discussed working on this issue first. Once completed, will move back to https://github.com/pyprobml-review/pyprobml-review/issues/22

**Comment by nitish1295** [comment]
Hi @karm-patel,

Based on the information I was able to gather from the meeting recording with Prof. @nipunbatra as well as the following resources. 

- https://docs.pyro.ai/en/stable/contrib.gp.html#module-pyro.contrib.gp.models.vgp
- https://pyro.ai/examples/gp.html

I am assuming you are looking for the first plot, I have shared the probability plots as well so that you can validate.

 | Predictions | ![image](https://user-images.githubusercontent.com/21181046/166937274-662c8677-f995-4521-838f-d22839d21d27.png) |
| :-: | :-: |
| Probability Iris Setosa - Class 0 |![image](https://user-images.githubusercontent.com/21181046/166929292-f78d2607-b60f-44c2-b2ec-ba73342b6a4e.png) |
|  Probability Iris Versicolor - Class 1| ![image](https://user-images.githubusercontent.com/21181046/166929358-ee776b81-2dae-472f-9207-29456328fec8.png) |
| Probability Iris Virginica - Class 2| ![image](https://user-images.githubusercontent.com/21181046/166936801-08f56753-6034-45fb-89dd-8e1ae4d10d34.png) |


**Please note, that for now, this code has not been included in the notebook. Once you finalize the graph I can go ahead and make changes to the latexified figure based on your suggestions. If this is incorrect then we can schedule a call for tommorow**

**Comment by nitish1295** [comment]
Hi @karm-patel

Based on our discussion, it seems you wanted decision boundaries along with the changes in probability near decision boundaries. Let me know if the following graph works. We can explicitly add decision boundaries on the plot as well if required.

Green - Virginica
Blue - Setosa
Purple - Versicolor

![image](https://user-images.githubusercontent.com/21181046/167238959-9cb485f2-7519-4332-9909-847c7ad9fae6.png)

Please note this is only done in rough, if this is acceptable I can create a function that will be able to do this for multiple classes.

cc @nipunbatra,@patel-zeel
